FROM php:7.2-fpm-alpine3.8

RUN echo "ipv6" >> /etc/modules
RUN apk add git
RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS && \
    apk add --no-cache --virtual .imagemagick-edge \
            --repository http://dl-3.alpinelinux.org/alpine/v3.6/main/ \
            --allow-untrusted \
        imagemagick \
        imagemagick-dev && \
    apk add --update --virtual .pecl-build-deps \
        icu-dev \
        curl-dev \
        freetype-dev \
        pcre-dev \
        postgresql-dev \
        libtool \
        libjpeg-turbo-dev \
        libpng-dev \
        libxml2-dev && \
    apk add \
        git \
        curl \
        bash \
        bash-completion \
        icu \
        vim \
        pcre \
        sqlite \
        freetype \
        libintl \
        libjpeg-turbo \
        imagemagick \
        libpng \
        libltdl \
        libxml2 \
        mysql-client \
        nodejs && \
    export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" && \
    pecl install \
        apcu \
        redis \
        imagick-3.4.3 && \
    docker-php-ext-enable imagick && \
    docker-php-ext-enable redis && \
    docker-php-ext-enable apcu && \
    docker-php-ext-configure gd \
        --with-gd \
        --with-freetype-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-configure bcmath && \
    docker-php-ext-install \
        soap \
        zip \
        curl \
        bcmath \
        exif \
        gd \
        iconv \
        intl \
        mbstring \
        pdo \
        pdo_mysql \
        opcache && \
    apk del \
        .pecl-build-deps .phpize-deps


# Configure version constraints
ENV PHP_ENABLE_XDEBUG=1 \
    VERSION_COMPOSER_ASSET_PLUGIN=^1.4.2 \
    VERSION_PRESTISSIMO_PLUGIN=^0.3.7 \
    PATH=/app:/app/vendor/bin:/root/.composer/vendor/bin:$PATH \
    TERM=linux \
    COMPOSER_ALLOW_SUPERUSER=1


# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
        --filename=composer \
        --install-dir=/usr/local/bin && \
    composer global require --optimize-autoloader \
        "fxp/composer-asset-plugin:${VERSION_COMPOSER_ASSET_PLUGIN}" \
        "hirak/prestissimo:${VERSION_PRESTISSIMO_PLUGIN}" && \
    composer global dumpautoload --optimize && \
    composer clear-cache

WORKDIR /app